version: '3'



volumes:
  share:
    driver: local
    driver_opts:
      device: ${PWD}/
      o: bind
      type: none

networks:
  net:
    driver: bridge

services:
  # next:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   container_name: next
  #   restart: always
  #   networks:a
  #     - net

  next:
    image: node:18.17.1
    working_dir: /home/app
    container_name: next
    restart: always
    networks:
      - net
    volumes:
      - share:/home/app
    command:
      - bash
      - "-c"
      - |
        apt update && apt list --upgradable &&
        yarn && yarn build && yarn start

    # ports:
    #   - "3000:3000"

  nginx:
    image: "nginx:latest"
    container_name: nginx
    restart: always
    networks:
      - net
    volumes:
      - ./configs/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./configs/nginx/conf.d:/etc/nginx/conf.d
    ports:
      - "80:80"
    depends_on:
      - next

